apiVersion: v1
kind: Service
metadata:
    name: snap-split-service
spec:
    selector:
        app: snap-split-server
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
    type: LoadBalancer
    loadBalancerIP: 10.10.10.10
